### PR TITLE
add pin-based security for doc requests

### PR DESCRIPTION
**Pull request by phluid61**
When configured (see `cfg.d/request_copy.pl`), this security model allows authors to respond to copy requests without having a valid login.

The pin-based model allows the contact author to respond whether they have an EPrints account associated with the specified email address or not. The normal repository authentication mechanism is not used, instead the presence of a random pin in the querystring identifies the contact author and grants access.

### CODE REVIEW

**Comment by jesusbagpuss** [comment]
Also related to: https://github.com/eprints/eprints/issues/192
May need an Admin/Manager screen to allow response to request?

**Comment by cziaarm** [comment]
This is almost "looks good to me".
- Checked functionality
- Added something to documentation (http://wiki.eprints.org/w/RequestEprint)
- No new phrases used (v. clever)
- runs OK on multiple repos
BUT
- Install not smooth: Bundled Session::Token ends up missing from @INC despite appearing to be OK on the face of it. Tested the above with pre-installed Session::Token.

**Comment by phluid61** [comment]
Yeah, if Session::Token is an issue it should be removed, and instead be listed as an EPrints dependency. I wasn't able to fully test that, since I already have it installed too.

(Feel free to send a PR to our branch if you know of a simple fix)

**Comment by MrkGrgsn** [comment]
I haven't checked it out but EPrints must be generating tokens for sessions somehow; perhaps the Session::Token dependency could be replaced with whatever that is?

**Comment by cziaarm** [comment]
John (jesusbagpuss) and I were just asking that same question. The "code" param for the token used by the current Request::Repond does this to generate a random string:

  my @a = ();
                srand;
                for(1..16) { push @a, sprintf( "%02X",int rand 256 ); }
                my $code = join( "", @a );

This is what DataObj::LoginTicket does:

sub _code
{
        my $ctx = Digest::MD5->new;
        srand;
        $ctx->add( $$, time, rand() );
        return $ctx->hexdigest;
}

I suspect that Session::Token does a more robust job than both of these (?), but if those other methods suffice then we would avoid the need to create a dependency.

Better would be to abstract the Token generation (EPrints::Utils perhaps?) and have it done conditionally so that if someone has Session::Token installed Eprints will use that. Otherwise use one of those first-principle methods.

**Comment by phluid61** [comment]
I update the PR using Request::Respond's code; if accepted we could update Request::Respond to use the new method in EPrints::Utils too, to keep things DRY.

Maybe even DataObj::LoginTicket.

**Comment by denics** [comment]
Dear all,

this is a great functionality. There is a specific motivation why it has not been merged yet?

**Comment by MrkGrgsn** [comment]
Glad to see this finally went in! 👍

**Pull request merged**
