### PR TITLE
Fix subjects/divisions being displayed in all languages after upgrade to 3.3.13

### LINKED ISSUE #295: subjects and divisions shown in both languages after upgrade to 3.3.13
After upgrade to eprints 3.3.13 debian package, our subject and department views started showing both languages for each value separated by comma as you can see here:

http://darhiv.ffzg.unizg.hr/view/subjects/

and here:

http://darhiv.ffzg.unizg.hr/view/divisions/

### PR DESCRIPTION
**Pull request by drtjmb**
This should fix #295 - apply the changes and regenerate subject/division view menus.

### CODE REVIEW

**Comment by sebastfr** [comment]
you added a "if( false )" statement in Multilang ;-)

**Comment by drtjmb** [comment]
I know 😉

On 15 Apr 2015 9:01 am, Sébastien François <notifications@github.com> wrote:

you added a "if( false )" statement in Multilang ;-)

**Comment by patrickmcsweeney** [comment]
Yeah I dont get that... Why not just remove the condition and the else
statement entirely?


On Wed, Apr 15, 2015 at 9:22 AM, Timothy Miles-Board <
notifications@github.com> wrote:

> I know [image: 😉]
>
> On 15 Apr 2015 9:01 am, Sébastien François <notifications@github.com>
> wrote:
>
> you added a "if( false )" statement in Multilang ;-)
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/eprints/eprints/pull/306#issuecomment-93251463>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eprints/eprints/pull/306#issuecomment-93257520>.
>



-- 

'But your intentions are beside the point, It's the outcome of your actions
that count...'

**Comment by jiadiyao** [comment]
Tim, I thought about this very fix before, but this means that render value for multilang would always render the first sub item (which may not be the item you want to render). Maybe this is ok because I cannot think of any other alternative solution!

**Comment by drtjmb** [comment]
The choice seemed to be between doing something sensible (rendering the name part in the appropriate language) and rendering a grim looking table. I suggest the former be the default behaviour - remove the if(false) I added and just do the default - if someone wants to do something different they should just use the render_value property to override (and hopefully produce something a bit less grim :-)

Tim

On 15 Apr 2015 11:38 am, Jiadi Yao <notifications@github.com> wrote:

Tim, I thought about this very fix before, but this means that render value for multilang would always render the first sub item (which may not be the item you want to render). Maybe this is ok because I cannot think of any other alternative solution!

**Comment by drtjmb** [comment]
@patrickmcsweeney - its a pull request, I wanted one of the core team to make that decision and modify it accordingly (I was just showing my working ;-)

**Pull request merged**
