### PR TITLE
Consider document security when adding to index

### PR DESCRIPTION
**Pull request by jesusbagpuss**
Don't add full-text index terms if the document isn't public.

See also https://github.com/eprints/eprints3.4/pull/44

### CODE REVIEW

**Comment by mpbraendle** [comment]
I think this is the wrong way. The document must be findable. Document security must be handled     in a later stage.

**Comment by jesusbagpuss** [comment]
@mpbraendle How much information from the full-text of the document should be put into the (publicly searchable) full-text index prior to the document becoming public?

Currently, you can infer some content of a document without having access to the document - which isn't good.

I wondered whether there needed to be multiple full-text-indices, possibly based on document security, and different searches would combine results from multiple of these.

If there isn't a consensus on how this should work, I suggest a repo-level config - something like:

```perl
$c->{full_text_indexing}->{document_security_to_include} = ['public', 'validuser'];
```
which can be tested in EPrints::MetaField::Subobject::get_index_codes_basic.

**Comment by mpbraendle** [comment]
We were discussing that problem in the current process of replacing Xapian with ElasticSearch. In our opinion, In any way, the document should be able to be matched with a query term or query terms that are in the full text. 
This does, however not mean, that the full-text or even a text snippet is to be exposed if the document security does not allow it; only the bibliographic data should be shown (user knows that "the documents exists, but cannot access it"). This is part of the document security model of EPrints and must be handled by EPrints render methods itself.
The full-text index, however, must be secured using authentication and other measures (allowed hosts and applications (repository) to access it, secure protocol). Having authentication and a stable search engine is one of the many reasons we are driving away from Xapian.

In addition, in the approach you give, each change of a document's security status would require reindexing.

**Comment by jesusbagpuss** [comment]
> In addition, in the approach you give, each change of a document's security status would require reindexing.

I think that any change where a document went from 'not public' to 'public' (or the other way round) would result in re-indexing - which is intended.

>This does, however not mean, that the full-text or even a text snippet is to be exposed

This is exactly what this patch is trying to address for a non-public document.
If eprint X has no public documents, you can search for (eprintid=X; documents = Y) . If a result is returned, one of the (not public) documents has term 'Y' in it. You have revealed a one-word snippet of the restricted document.

Would having e.g. `documents_$security` indexes (one for each security value) work?
- if you are not signed in, your search can use documents_public index
- if you are signed-in, but not as a repo-staff user, your search would use documents_public and documents_validuser indexes
- if you are signed in as an admin user, your search would use documents_public, documents_validuser and documents_staffonly indexes together

**Comment by mpbraendle** [comment]
A user guessing a document this way would have to inspect the metadata of the hit first for occurence of this term.
Second, to find out about the content of the document at least n! phrase guesses would be required (n = count of terms in the document), if position of terms is important (and that is to understand the document).

**Comment by jenswitzel** [comment]
@jesusbagpuss: so am i right, that you need one index for every role - anonymous, staff, admin!? And you have to shift all content from iône index to the other, if any status changes? 

Special case: What if (as we use this) usergroups do not want to share their content with others while it's under construction and not in the live archive? So the more roles/groups/functions we get, we need a more and more complex matrix of indexes ...

At our point of view, we need to seperate any search engine from the role management of the application (eprints) and let eprints be the (only) proxy to add security. No other application should get access to that index.

**Comment by jesusbagpuss** [comment]
Hi @jenswitzel,
The change in this PR means full-text terms for non-public documents are *not* added to the EPrints (internal) full-text search index.

From @mpbraendle it sounds like the current behaviour is wanted - although that use-case might be covered by Xapian or other indexing that happens?

Do your users search for terms within their full-text documents, within the EPrints interface, and while the EPrints are not public?

Do you use the EPrints internal index for some purposes, and Xapian for public searching?

**Comment by phluid61** [comment]
> A user guessing a document this way would have to inspect the metadata of the hit first for occurence of this term.
> Second, to find out about the content of the document at least n! phrase guesses would be required (n = count of terms in the document), if position of terms is important (and that is to understand the document).

If the goal is not to recreate the hidden document, but to steal information, then that's not required.  Hypothetical (illustrative) example: if the non-public documents contain potentially personally identifying information about research subjects, for example, I could use targetted searches to infer information about them.

**Comment by mpbraendle** [comment]
@jesusbagpuss We use both: Xapian for quick search, and the EPrints full-text SQL index in advanced search. Both public.

@jesusbagpuss AFAIK, change of one field only (e.g. the security status) only triggers reindexing of that field. Hence, you should check also that the full document reindex will be triggered.

@phluid61 agreed. However, there may be different use cases. Publication repositories in most cases are secondary publication containers for published scientific documents - the (embargoed) document usually has already been published on another platform (e.g. a publisher's platform) and is accessible there. If you plan however, to operate a dark archive, then your argument holds true. But then I would hide access (and search) completely behind a login.

**Comment by alex-wreschnig** [comment]
I'm in one of the affected institutions, part of our library's IT group. We don't have many use-cases where this would come into play, but the cases we do have are important. We're quite interested in seeing a solution implemented.

**Pull request merged**
