### PR TITLE
Update autoconfiguration

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
This replaces PR #385 which was against the unmaintained master branch.

**Comment by phluid61** [comment]
As I'm someone who knows very little about package maintenance and auto-conf tools and the like, can you briefly explain the motivation for this change?

**Comment by stweil** [comment]
The first two patches fix warnings from the autotools (that's how I noticed that there are problems). More details are in the commit messages of these patches. The third patch tells git to ignore the files which were built by the autotools.

**Comment by stweil** [comment]
Ping?

**Pull request merged**
